### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by robert-hoekstra** [Wiebsonice/functional-programming#3]
Een klein lijstje adhv de rubric:

- [x] gitignore

   Check je .gitignore. Misschien heb je er al eentje en dat die zelf ook op de ignore staat. Echter zit er ook nog een .gitattributes bestand in je repo.
- [x] link to live demo on github pages

   Ik heb geen link kunnen vinden naar jouw Github Pages
- [x] description

   Beschrijving van jouw daadwerkelijke product vind ik lastig om te vinden. Waarschijnlijk is die er momenteel ook nog niet?
- [x] concept

   Toffe concepten! Maar met welk concept ga je verder een waarom?
- [x] image

   Je code heb je heel fijn uitgelegd. Lekker casual maar ook veel beeldmateriaal waarin je je code laat zien. Hetzelfde geldt over je concepten. Wederom kom ik nergens afbeeldingen tegen van jouw product.
- [x] link to example used to build visualization

   Ga je een voorbeeld gebruiken? Graag een linkje toevoegen!
- [x] data used (what's done with invalid and empty values?)

   Je laat heel duidelijk zien hoe je met je datacleaning omgaat!
- [x] (link to) functional pattern

   Over je functionele patroon kan ik niet meer zeggen dat je goed aan de slag gaat met de yearConverter. Misschien zie ik wat over het hoofd?
- [x] plagiarism and acknowledgements

   Waar heb je je code vandaan gehaald? Heb je alles zelf verzonnen?

**Comment by Wiebsonice** [comment]
Added missing points
